"""Generate tex/rltable.tex from receipts/rl_arms_2v2.json."""
import json, os
R = os.environ.get("BRACE_ROOT", os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
d = json.load(open(f"{R}/surface/receipts/rl_arms_2v2.json"))
C = [d["control 1"], d["control 2"]]; S = [d["selected 1"], d["selected 2"]]
def pf(p): return "$<10^{-4}$" if p < 1e-4 else f"${p:.2f}$"
rows = [
 "Steps & " + " & ".join(str(x["steps"]) for x in C+S) + r" \\",
 r"Non-degenerate groups & \multicolumn{2}{c}{$9.2\%$} & \multicolumn{2}{c}{$\mathbf{64.2\%}$} \\",
 "Reward, 1st half & " + " & ".join(f"{x['first']:.4f}" for x in C+S) + r" \\",
 "Reward, 2nd half & " + " & ".join(f"{x['second']:.4f}" for x in C+S) + r" \\",
 r"$\Delta$ & " + " & ".join(f"${x['delta']:+.4f}$" for x in C) + " & " +
   " & ".join(f"$\\mathbf{{{x['delta']:+.4f}}}$" for x in S) + r" \\",
 "Permutation $p$ & " + " & ".join(pf(x["p"]) for x in C+S) + r" \\",
]
open(f"{R}/surface/paper/tex/rltable.tex","w").write(
 "% generated by make_rltable.py -- do not edit\n"
 "\\begin{tabular}{lrrrr}\n\\toprule\n"
 " & \\multicolumn{2}{c}{Unselected} & \\multicolumn{2}{c}{Selected} \\\\\n"
 "\\cmidrule(lr){2-3}\\cmidrule(l){4-5}\n"
 " & Run 1 & Run 2 & Run 1 & Run 2 \\\\\n\\midrule\n"
 + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
print("  wrote tex/rltable.tex")
