"""Regenerate tex/headtohead.tex from logs and history files. All numbers extracted, none typed."""
import json, os, re
R = os.environ.get("BRACE_ROOT", os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
CEIL = 0.2813   # qwen full-surface success on pool_big320, from banked no-edit replicates

def discord_decisions(log):
    seen, out = set(), []
    for line in open(log, errors="ignore"):
        m = re.search(r"\[discord-awm\] (r\d+c\d+) advertised=(\d+) b=(\d+) c=(\d+) p=([\d.]+) "
                      r"tasks=(\d+)/\d+ (ACCEPT|reject)", line)
        if m and m.group(1) not in seen:
            seen.add(m.group(1))
            out.append({"id": m.group(1), "adv": int(m.group(2)), "b": int(m.group(3)),
                        "c": int(m.group(4)), "p": float(m.group(5)), "tasks": int(m.group(6)),
                        "accept": m.group(7) == "ACCEPT"})
    return out

def discord_final(log):
    obj = eps = None
    for line in open(log, errors="ignore"):
        m = re.search(r"round \d+ -> success=([\d.]+) advertised=\d+ episodes-so-far=(\d+)", line)
        if m: obj, eps = float(m.group(1)), int(m.group(2))
        m0 = re.search(r"r0 incumbent success=([\d.]+)", line)
        if m0 and obj is None: obj = float(m0.group(1))
    return obj, eps

def naive_summary(hist):
    h = json.load(open(hist))
    acc = h["accepts"]
    return {"accepts": len(acc), "good": sum(1 for a in acc if a["net_restored"] > 0),
            "bad": sum(1 for a in acc if a["net_restored"] < 0),
            "true": h["true_final_objective"], "rep": h["remembered_final"],
            "eps": h["total_episodes"]}

rows, summary = [], {}
for regime, dlog, nhist in [
        ("shallow", f"{R}/logs/awm_discord.log", f"{R}/work/awm_naive/history_naive_awm.json"),
        ("deep", f"{R}/logs/awm_discord_deep.log", f"{R}/work/awm_naive_deep/history_naive_awm.json")]:
    dec = discord_decisions(dlog)
    dobj, deps = discord_final(dlog)
    if deps is None:                      # loop stopped before a round summary: bill it by hand
        deps = 640 + sum(x["tasks"] * 2 for x in dec)
    dacc = sum(1 for x in dec if x["accept"])
    n = naive_summary(nhist)
    summary[regime] = {"discord": {"accepts": dacc, "true": dobj, "episodes": deps,
                                   "decisions": dec},
                       "deployed": n}
    rows.append(f"{regime} & deployed & {n['accepts']} ({n['good']}/{n['bad']}) & "
                f"{n['true']:.4f} ({100*n['true']/CEIL:.0f}\\%) & "
                f"{n['rep']:.4f} (${100*(n['rep']/n['true']-1):+.0f}\\%$) & {n['eps']:,} \\\\")
    rows.append(f"{regime} & \\textsc{{Discord}} & {dacc} ({dacc}/0) & "
                f"{dobj:.4f} ({100*dobj/CEIL:.0f}\\%) & \\emph{{truthful}} & {deps:,} \\\\")
    if regime == "shallow": rows.append("\\addlinespace[3pt]")

open(f"{R}/surface/paper/tex/headtohead.tex", "w").write(
    "% generated by make_headtohead.py -- do not edit\n"
    "\\begin{tabular}{@{}llcccr@{}}\n\\toprule\n"
    "regime & rule & accepts (good/bad) & true final & self-reported & episodes \\\\\n\\midrule\n"
    + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
json.dump(summary, open(f"{R}/surface/receipts/regime_summary.json", "w"), indent=2)
for r in rows: print("  " + r)
print("\n  shallow DISCORD decisions:", [(x["id"], x["b"], x["c"], x["tasks"]) for x in summary["shallow"]["discord"]["decisions"]])
print("  deep DISCORD decisions:   ", [(x["id"], x["b"], x["c"], x["tasks"], x["accept"]) for x in summary["deep"]["discord"]["decisions"]])
